### ISSUE TITLE
Create Initial User Design

### ISSUE THREAD

**Issue by SarahMurguia** [SarahMurguia/FreeFlow#1]
Make a design on figma or paper and upload pictures! We'll vote on design later.

**Comment by SarahMurguia** [comment]
My initial design https://www.figma.com/file/JjgGedsEr2yRb1lIEGmIU1/FreeFlow?node-id=0%3A1
<img width="1113" alt="Screen Shot 2019-09-12 at 5 27 48 PM" src="https://user-images.githubusercontent.com/44075242/64822308-bb848600-d582-11e9-9630-8c4dbe61ed90.png">

**Comment by claireymcmanus** [comment]
![image](https://user-images.githubusercontent.com/38960862/64887570-ee885180-d636-11e9-8211-f81873c28f88.png)

**Comment by wakh** [comment]
https://app.sympli.io/p/41c52b237acf65b733d7cbc49777ff0e16ed740897
<table>
<tbody>
<tr>
<td>
<p>Main </p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915111-aa2bad00-d72d-11e9-9636-c1aa52d9955a.png" width="140" height="140" /></p>
</td>
<td>
<p>Sign-up</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915112-aef06100-d72d-11e9-99a1-3c565c52e44f.png" width="140" height="140" /></p>
</td>
<td>
<p>Forgot Password</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915113-b283e800-d72d-11e9-8176-e9f7459ba5f1.png" width="140" height="140" /></p>
</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>
<p>Status</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915114-bca5e680-d72d-11e9-965a-14c052d5618d.png" alt="" width="140" height="140" /></p>
</td>
<td>
<p>Household</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915115-c0396d80-d72d-11e9-89cd-eff571d2fbdf.png" alt="" width="140" height="140" /></p>
</td>
<td>
<p>My Sevices</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915118-c29bc780-d72d-11e9-9504-60398a72c0e4.png" alt="" width="140" height="140" /></p>
</td>
<td>
<p>Profile</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915120-c4fe2180-d72d-11e9-9e29-3d066b2507f8.png" width="140" height="140" /></p>
</td>
</tr>
<tr>
<td>&nbsp;</td>
<td>
<p>Invite</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915122-c92a3f00-d72d-11e9-8844-f943baf04cec.png" alt="" width="140" height="140" /></p>
</td>
<td>
<p>Add Sevice</p>
<p><img src="https://user-images.githubusercontent.com/55111948/64915177-794c7780-d72f-11e9-92ae-0d19e32d07c9.png" alt="" width="140" height="140" /></p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>

**Comment by willim15** [comment]
**WIRE FRAME**

![Portfolio](https://user-images.githubusercontent.com/35747109/64982394-1ae8db80-d88c-11e9-95d8-9cf665aa68c9.jpg)
![Portfolio (3)](https://user-images.githubusercontent.com/35747109/64982395-1ae8db80-d88c-11e9-8f92-31fcccb0b5af.jpg)
![Portfolio (2)](https://user-images.githubusercontent.com/35747109/64982396-1b817200-d88c-11e9-8d2f-62c3655e4e36.jpg)
![Portfolio (1)](https://user-images.githubusercontent.com/35747109/64982397-1b817200-d88c-11e9-86cb-1f2f26bde2f3.jpg)

**Comment by SarahMurguia** [comment]
Final Design: https://www.figma.com/file/WIaPPaP5RoE2RLHBjFk80Y/FreeFlowOffical?node-id=0%3A1
