### ISSUE TITLE
User forgets a password

### ISSUE THREAD

**Issue by SarahMurguia** [SarahMurguia/FreeFlow#10]
Need to send email to user when reminder of password

**Comment by claireymcmanus** [comment]
https://kinsta.com/knowledgebase/free-smtp-server/

**Comment by claireymcmanus** [comment]
UI and database connection finished, still need to figure out how to send email from application

**Comment by claireymcmanus** [comment]
http://sahatyalkabov.com/how-to-implement-password-reset-in-nodejs/

**Comment by SarahMurguia** [comment]
using a form instead
