### ISSUE TITLE
Change Database Layout

### ISSUE THREAD

**Issue by SarahMurguia** [SarahMurguia/FreeFlow#15]
User Database:
Id(int), Username(string), Email(string), Password(string), Net1(string), Net2(string), Net3(string)

Service Database per Service:
Id(int), Service_Email(string), Service_Password(string), Net1(0,1), Net2(0,1), Net3(0,1)
0 if user cannot user on given network
1 if user can use

**Comment by claireymcmanus** [comment]
4 new databases created:
**users**(userid[_int_], username[_varchar_], email[_varchar_], password[_varchar_], network1[_varchar_], network2[_varchar_], network3[_varchar_])
**netflix**(userid[_int_], service_username[_varchar_], service_password[_varchar_], network1[_boolean_], network2[_boolean_], network3[_boolean_])
**hulu**(userid[_int_], service_username[_varchar_], service_password[_varchar_], network1[_boolean_], network2[_boolean_], network3[_boolean_])
**hbo**(userid[_int_], service_username[_varchar_], service_password[_varchar_], network1[_boolean_], network2[_boolean_], network3[_boolean_])
Network values default set to NULL
